// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX1OTOQtQNosJNGEyEOAT50nSzD4-mMKk',
    appId: '1:456350047164:web:9a3666656e17591b84e9b9',
    messagingSenderId: '456350047164',
    projectId: 'activepals-2025',
    authDomain: 'activepals-2025.firebaseapp.com',
    storageBucket: 'activepals-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPCheL5r6ty8Wjy2mWkKFkKtDdlBrzPEg',
    appId: '1:456350047164:android:500bf13efb5323a784e9b9',
    messagingSenderId: '456350047164',
    projectId: 'activepals-2025',
    storageBucket: 'activepals-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACBssUSFUHvWCarHWF24kXMeDeCGmoDGI',
    appId: '1:456350047164:ios:1606d62005623eea84e9b9',
    messagingSenderId: '456350047164',
    projectId: 'activepals-2025',
    storageBucket: 'activepals-2025.firebasestorage.app',
    iosBundleId: 'com.example.activePals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACBssUSFUHvWCarHWF24kXMeDeCGmoDGI',
    appId: '1:456350047164:ios:1606d62005623eea84e9b9',
    messagingSenderId: '456350047164',
    projectId: 'activepals-2025',
    storageBucket: 'activepals-2025.firebasestorage.app',
    iosBundleId: 'com.example.activePals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX1OTOQtQNosJNGEyEOAT50nSzD4-mMKk',
    appId: '1:456350047164:web:e14d9e040b1165ed84e9b9',
    messagingSenderId: '456350047164',
    projectId: 'activepals-2025',
    authDomain: 'activepals-2025.firebaseapp.com',
    storageBucket: 'activepals-2025.firebasestorage.app',
  );
}